# KubeVirt CR for dev (software emulation, no KVM required)
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      useEmulation: true
      featureGates:
        - GPU
        - HostDevices
    permittedHostDevices:
      pciHostDevices:
        - pciVendorSelector: "10DE:"
          resourceName: nvidia.com/gpu-passthrough
          externalResourceProvider: false
  workloadUpdateStrategy:
    workloadUpdateMethods:
      - LiveMigrate
