apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - compute-operator.yaml
  - vm-operator.yaml
  - notebook-operator.yaml
  - gpujob-operator.yaml
  - storage-operator.yaml
  - network-operator.yaml
