/*
Copyright 2026 The KCP Reference Architecture Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// gen-core-apiexport merges all individual APIExport YAMLs under config/kcp/
// into a single "cloud.platform" APIExport that covers every API group.
// This lets tenants bind a single export to get access to all platform resources.
//
// Usage (via make codegen):
//
//	go run ./hack/gen-core-apiexport --config-dir config/kcp --output config/kcp/apiexport-cloud.platform.yaml
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"
)

// apiExport is a minimal representation of an APIExport YAML for merging.
type apiExport struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
	Metadata   struct {
		Name string `yaml:"name"`
	} `yaml:"metadata"`
	Spec struct {
		PermissionClaims []map[string]interface{} `yaml:"permissionClaims,omitempty"`
		Resources        []map[string]interface{} `yaml:"resources,omitempty"`
	} `yaml:"spec"`
	Status interface{} `yaml:"status,omitempty"`
}

func main() {
	configDir := flag.String("config-dir", "config/kcp", "directory containing individual APIExport YAML files")
	output := flag.String("output", "config/kcp/apiexport-cloud.platform.yaml", "path for the generated merged APIExport")
	flag.Parse()

	entries, err := os.ReadDir(*configDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading config dir %s: %v\n", *configDir, err)
		os.Exit(1)
	}

	// permissionClaims key = "group/resource" for deduplication.
	type claimKey struct{ group, resource string }
	seenClaims := map[claimKey]bool{}
	var mergedClaims []map[string]interface{}
	var mergedResources []map[string]interface{}

	// Process files alphabetically, skip the output file itself and non-apiexport files.
	outputBase := filepath.Base(*output)
	var files []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if name == outputBase {
			continue // skip previously generated output
		}
		if !strings.HasPrefix(name, "apiexport-") || !strings.HasSuffix(name, ".yaml") {
			continue
		}
		files = append(files, filepath.Join(*configDir, name))
	}
	sort.Strings(files)

	for _, path := range files {
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error reading %s: %v\n", path, err)
			os.Exit(1)
		}

		var export apiExport
		if err := yaml.Unmarshal(data, &export); err != nil {
			fmt.Fprintf(os.Stderr, "error parsing %s: %v\n", path, err)
			os.Exit(1)
		}

		// Merge permission claims (deduplicate by group+resource).
		for _, claim := range export.Spec.PermissionClaims {
			group, _ := claim["group"].(string)
			resource, _ := claim["resource"].(string)
			key := claimKey{group: group, resource: resource}
			if !seenClaims[key] {
				seenClaims[key] = true
				mergedClaims = append(mergedClaims, claim)
			}
		}

		// Merge resources (all included; each has a unique schema name).
		mergedResources = append(mergedResources, export.Spec.Resources...)
	}

	// Build the merged APIExport.
	merged := map[string]interface{}{
		"apiVersion": "apis.kcp.io/v1alpha2",
		"kind":       "APIExport",
		"metadata": map[string]interface{}{
			"name": "cloud.platform",
		},
		"spec": map[string]interface{}{
			"permissionClaims": mergedClaims,
			"resources":        mergedResources,
		},
		"status": map[string]interface{}{},
	}

	out, err := yaml.Marshal(merged)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error marshaling output: %v\n", err)
		os.Exit(1)
	}

	header := "# Code generated by hack/gen-core-apiexport. DO NOT EDIT.\n" +
		"# Run 'make codegen' to regenerate.\n"

	if err := os.WriteFile(*output, append([]byte(header), out...), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (merged %d exports, %d resources, %d permission claims)\n",
		*output, len(files), len(mergedResources), len(mergedClaims))
}
